name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry and build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all --check
        # `--all` is only important in workspaces, but it's here and it's chilling with the homies, so it can stay

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features --keep-going -- -D warnings

      - name: Run tests
        run: cargo test --verbose
